# Generated by Django 2.2.10 on 2020-06-05 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20200605_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
