# Generated by Django 2.2.10 on 2020-06-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_auto_20200609_0052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='files',
            new_name='file',
        ),
    ]
